import test from 'node:test';import assert from 'node:assert/strict';
import {relativeHumidity,convertScalar,validSelection,availableLevels,sampleScalar,contourSegments} from '../lib/weather-data.mjs';import {indexedRanges,jmaScalarMessage,validateRequest,singleURL} from '../lib/weather-raw.mjs';
test('only actual pressure-level products selectable',()=>{for(const m of ['gfs','ecmwf','aifs-single','gefs','aigefs','icon','cmce','jma','era5'])for(const f of ['humidity','height','temperature'])assert.ok(validSelection(m,f,500));assert.equal(validSelection('weathernext2','humidity',500),false);assert.equal(validSelection('gfs','humidity',10),false);assert.deepEqual(availableLevels('jma','humidity'),[925,850,700,500,300])});
test('geopotential and temperatures retain physical units',()=>{assert.equal(convertScalar(9806.65,'z','height'),1000);assert.equal(convertScalar(5500,'gh','height'),5500);assert.equal(convertScalar(273.15,'t','temperature'),0);assert.ok(Number.isNaN(convertScalar(1e30,'gh','height')));assert.ok(Math.abs(relativeHumidity(.003811,273.15,1000)-100)<.2);assert.ok(Number.isNaN(relativeHumidity(-1,273,500)))});
test('longitude wrap and missing cells',()=>{const g={west:0,east:360,south:0,north:1,cols:3,rows:2,lonStep:180,latStep:1};assert.equal(sampleScalar(g,[1,3,1,1,3,1],-90,.5),2);assert.equal(sampleScalar(g,[1,NaN,1,1,3,1],90,.5),null);assert.equal(sampleScalar(g,[1,3,1,1,3,1],90,5),null)});
test('NOAA index selects exact pressure not adjacent level',()=>{const idx='1:0:d:HGT:500 mb:anl\n2:200:d:RH:500 mb:anl\n3:400:d:RH:700 mb:anl\n4:600:d:TMP:500 mb:anl';assert.deepEqual(indexedRanges(idx,'gfs','humidity',500),[{start:200,end:399}]);assert.throws(()=>indexedRanges(idx,'gfs','humidity',850))});
test('AIFS RH requires q and T with matching level',()=>{const idx=[{param:'q',levelist:'500',_offset:0,_length:200},{param:'t',levelist:'500',_offset:200,_length:200}].map(JSON.stringify).join('\n');assert.equal(indexedRanges(idx,'aifs-single','humidity',500).length,2);assert.throws(()=>indexedRanges(idx,'aifs-single','humidity',700))});
test('invalid inputs do not build arbitrary fetches',()=>{assert.throws(()=>validateRequest('x','humidity',500,'2026100500',0));assert.throws(()=>validateRequest('gfs','height',500,'2026023000',0));assert.throws(()=>validateRequest('icon','height',500,'2026100500',181));assert.ok(singleURL('icon','2026100500',6,'height',500).includes('/fi/'));assert.throws(()=>jmaScalarMessage(new Uint8Array(109),new Uint8Array(62706),0,500,'height'))});
test('contours avoid missing data and use gpm coordinates',()=>{const g={west:0,south:0,cols:2,rows:2,lonStep:1,latStep:1};assert.equal(contourSegments(g,[0,120,0,120],60,1).length,2);assert.equal(contourSegments(g,[0,NaN,0,120],60,1).length,0)});

test('surface availability never invents unsupported model fields',async()=>{const {supportsField,availableLevels,minimumStep}=await import('../lib/weather-data.mjs');assert.deepEqual(availableLevels('ecmwf','rain24'),[0]);assert.equal(minimumStep('rain24'),24);assert.equal(supportsField('aifs-single','cape'),false);assert.equal(supportsField('jma','rain6'),false);assert.equal(supportsField('gfs','rainTotal'),false);});

test('sea-level pressure contours use hPa at 4 hPa intervals',()=>{const g={west:120,east:121,south:23,north:24,cols:2,rows:2,lonStep:1,latStep:1};const lines=contourSegments(g,[1002,1010,1002,1010],4,1);assert.deepEqual(lines.map(l=>l.height),[1004,1008]);assert.ok(lines.every(l=>l.coordinates.length===2&&l.coordinates.every(([x,y])=>x>=120&&x<=121&&y>=23&&y<=24)));assert.deepEqual(contourSegments(g,[NaN,1010,1002,1010],4,1),[]);});
