'use client';
import {useEffect,useRef} from 'react';
import Map from 'ol/Map';import View from 'ol/View';import ImageLayer from 'ol/layer/Image';import ImageCanvas from 'ol/source/ImageCanvas';import VectorLayer from 'ol/layer/Vector';import VectorSource from 'ol/source/Vector';import GeoJSON from 'ol/format/GeoJSON';import Feature from 'ol/Feature';import Point from 'ol/geom/Point';import LineString from 'ol/geom/LineString';import {Style,Stroke,Fill,Circle as CircleStyle,Text} from 'ol/style';import {fromLonLat,toLonLat} from 'ol/proj';import {defaults as interactions} from 'ol/interaction';import {defaults as controls} from 'ol/control';import {sampleScalar,scalarColor,contourSegments} from '@/lib/weather-data.mjs';import 'ol/ol.css';
export default function WeatherMap(p:{data:any;extra:any;contours:boolean;point:any;onPoint:(v:any)=>void;onReady:(v:any)=>void}){const host=useRef<HTMLDivElement>(null),map=useRef<Map|null>(null),raster=useRef<ImageCanvas|null>(null),lines=useRef(new VectorSource()),arrows=useRef(new VectorSource()),selection=useRef(new VectorSource()),current=useRef(p);current.current=p;
 useEffect(()=>{const source=new ImageCanvas({ratio:1,projection:'EPSG:3857',canvasFunction:(extent,resolution,pixelRatio,size)=>{const canvas=document.createElement('canvas');canvas.width=size[0];canvas.height=size[1];const d=current.current.data;if(!d)return canvas;const w=Math.min(850,Math.ceil(size[0]/3)),h=Math.max(1,Math.round(w*size[1]/size[0])),small=document.createElement('canvas');small.width=w;small.height=h;const sc=small.getContext('2d')!,image=sc.createImageData(w,h);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const [lon,lat]=toLonLat([extent[0]+(x+.5)/w*(extent[2]-extent[0]),extent[3]-(y+.5)/h*(extent[3]-extent[1])]),v=sampleScalar(d.grid,d.values,lon,lat);if(v===null)continue;const rgb=scalarColor(v,d.field,parseInt(d.level)),i=(y*w+x)*4;image.data[i]=rgb[0];image.data[i+1]=rgb[1];image.data[i+2]=rgb[2];image.data[i+3]=235}sc.putImageData(image,0,0);canvas.getContext('2d')!.drawImage(small,0,0,canvas.width,canvas.height);return canvas}});raster.current=source;
 const m=new Map({target:host.current!,layers:[new VectorLayer({source:new VectorSource({url:'/data/land.json',format:new GeoJSON()}),style:new Style({fill:new Fill({color:'#1a3444'})})}),new ImageLayer({source}),new VectorLayer({source:new VectorSource({url:'/data/coastline.json',format:new GeoJSON()}),style:new Style({stroke:new Stroke({color:'#f2f5f0bd',width:.8})})}),new VectorLayer({source:lines.current,declutter:true}),new VectorLayer({source:arrows.current}),new VectorLayer({source:selection.current,style:new Style({image:new CircleStyle({radius:5,fill:new Fill({color:'#a6ded3'}),stroke:new Stroke({color:'#fff',width:2})})})})],view:new View({center:fromLonLat([135,25]),zoom:3.2,minZoom:1,maxZoom:9,multiWorld:true,enableRotation:false}),interactions:interactions({pinchRotate:false,altShiftDragRotate:false}),controls:controls({zoom:false,rotate:false,attribution:false})});map.current=m;
 m.on('singleclick',e=>{const [lon,lat]=toLonLat(e.coordinate),d=current.current.data;if(!d)return;current.current.onPoint({lon,lat,value:sampleScalar(d.grid,d.values,lon,lat),x:e.pixel[0],y:e.pixel[1],width:m.getSize()![0],height:m.getSize()![1]})});m.on('moveend',()=>drawArrows());m.on('movestart',()=>current.current.onPoint(null));current.current.onReady({zoom:(v:number)=>m.getView().animate({zoom:(m.getView().getZoom()||3)+v,duration:200}),region:(id:string)=>{const [lon,lat,z]=({pacific:[135,25,3.2],taiwan:[121,23.5,5.5],world:[0,10,1.3],europe:[15,48,3.4],america:[-95,35,3]} as any)[id]||[135,25,3.2];m.getView().animate({center:fromLonLat([lon,lat]),zoom:z,duration:300})}});const resize=new ResizeObserver(()=>m.updateSize());resize.observe(host.current!);return()=>{resize.disconnect();m.setTarget(undefined);map.current=null};},[]);
 const drawArrows=()=>{arrows.current.clear();const m=map.current,u=current.current.extra?.u,v=current.current.extra?.v;if(!m||!u||!v)return;const size=m.getSize()!;for(let y=20;y<size[1];y+=48)for(let x=20;x<size[0];x+=48){const coord=m.getCoordinateFromPixel([x,y]),[lon,lat]=toLonLat(coord),a=sampleScalar(u.grid,u.values,lon,lat),b=sampleScalar(v.grid,v.values,lon,lat);if(a===null||b===null)continue;const f=new Feature(new Point(coord));f.setStyle(new Style({text:new Text({text:'↑',rotation:Math.atan2(a,b),font:'24px sans-serif',fill:new Fill({color:'#ecf5e5'}),stroke:new Stroke({color:'#163040',width:2})})}));arrows.current.addFeature(f)}};
 useEffect(()=>{drawArrows()},[p.extra]);
 useEffect(()=>{raster.current?.changed();lines.current.clear();if((p.data?.field==='height'||p.data?.field==='pressure'||p.extra?.height)&&p.contours){const d=p.extra?.height||p.data,pressure=d.field==='pressure',segments=contourSegments(d.grid,d.values,pressure?4:60,pressure?1:Math.max(1,Math.round(1/d.grid.lonStep)));for(let i=0;i<segments.length;i++){const seg=segments[i],f=new Feature(new LineString(seg.coordinates.map((c:number[])=>fromLonLat(c))));f.setStyle(new Style({stroke:new Stroke({color:seg.height%(pressure?20:300)===0?'#fff':'#ffffffa8',width:seg.height%(pressure?20:300)===0?1.5:.7}),...(i%180===0?{text:new Text({text:String(seg.height),font:'11px sans-serif',fill:new Fill({color:'#fff'}),stroke:new Stroke({color:'#172c40',width:3})})}:{})}));lines.current.addFeature(f)}}},[p.data,p.contours,p.extra]);
 useEffect(()=>{selection.current.clear();if(p.point)selection.current.addFeature(new Feature(new Point(fromLonLat([p.point.lon,p.point.lat]))))},[p.point]);return <div ref={host} className="weather-map" aria-label="可移動及縮放的全球天氣圖"/>}
