'use client';
import {radarWorker} from '@/lib/portable-workers';
import {useEffect,useRef,useState} from 'react';
import Map from 'ol/Map';import TileLayer from 'ol/layer/Tile';import ImageLayer from 'ol/layer/Image';import XYZ from 'ol/source/XYZ';import ImageStatic from 'ol/source/ImageStatic';import Projection from 'ol/proj/Projection';import {addProjection,addCoordinateTransforms,transform} from 'ol/proj';import proj4 from 'proj4';import {createXYZ} from 'ol/tilegrid';import {selectRadarFrame} from '@/lib/radar.mjs';
const crs=new Projection({code:'CWA-TWD67',units:'degrees',extent:[115,18,126.5,29]});addProjection(crs);
const p67='+proj=tmerc +lat_0=0 +lon_0=121 +k=0.9999 +x_0=250000 +y_0=0 +a=6378160 +rf=298.25',p97='+proj=tmerc +lat_0=0 +lon_0=121 +k=0.9999 +x_0=250000 +y_0=0 +ellps=GRS80';
addCoordinateTransforms(crs,'EPSG:3857',c=>{if(!c.every(Number.isFinite))return [NaN,NaN];const xy=proj4('+proj=longlat +a=6378160 +rf=298.25',p67,c);if(!xy.every(Number.isFinite))return [NaN,NaN];return transform(proj4(p97,'EPSG:4326',[xy[0]+828.589,xy[1]-206.915]),'EPSG:4326','EPSG:3857')},c=>{if(!c.every(Number.isFinite))return [NaN,NaN];const xy=proj4('EPSG:4326',p97,transform(c,'EPSG:3857','EPSG:4326'));if(!xy.every(Number.isFinite))return [NaN,NaN];return proj4(p67,'+proj=longlat +a=6378160 +rf=298.25',[xy[0]-828.589,xy[1]+206.915])});
export function useRadar(map:React.RefObject<Map|null>,p:{time:string,playing:boolean,nextTimes:string[],radars:string[],onRadarReady:(b:boolean)=>void,onRadarStatus:(s:string)=>void}){
 const [manifests,setManifests]=useState<Record<string,any>>({}),cb=useRef(p),layers=useRef<any[]>([]),cache=useRef(new globalThis.Map<string,Promise<any>>()),urls=useRef<string[]>([]);cb.current=p;
 useEffect(()=>{let dead=false;async function refresh(){for(const provider of p.radars)try{const r=await fetch('/api/radar?provider='+provider);const j:any=await r.json();if(!r.ok)throw Error(j.error);if(!dead)setManifests(old=>({...old,[provider]:j}))}catch(e){if(!dead){setManifests(old=>({...old,[provider]:{frames:[],error:String(e)}}))}}}refresh();const timer=setInterval(refresh,60000);return()=>{dead=true;clearInterval(timer)}},[p.radars.join(',')]);
 function cwa(time:string){let job=cache.current.get(time);if(job)return job;job=(async()=>{const r=await fetch('/api/radar?provider=cwa&time='+encodeURIComponent(time));if(!r.ok){const j:any=await r.json();throw Error(j.error)}const bytes=await r.arrayBuffer();return await new Promise<any>((resolve,reject)=>{const worker=new radarWorker();worker.onmessage=e=>{worker.terminate();if(e.data.error)reject(Error(e.data.error));else{const url=URL.createObjectURL(e.data.blob);urls.current.push(url);while(urls.current.length>12)URL.revokeObjectURL(urls.current.shift()!);resolve({...e.data,url})}};worker.onerror=()=>{worker.terminate();reject(Error('雷達解碼失敗'))};worker.postMessage(bytes,[bytes])})})();cache.current.set(time,job);job.catch(()=>cache.current.delete(time));while(cache.current.size>6)cache.current.delete(cache.current.keys().next().value!);return job;}
 useEffect(()=>{const m=map.current;if(!m||!p.time)return;let cancelled=false,adopted=false;const pendingLayers:any[]=[];cb.current.onRadarReady(false);
 (async()=>{const reports:string[]=[];for(const provider of p.radars){const manifest=manifests[provider];if(!manifest){reports.push((provider==='jma'?'日本':'臺灣')+'雷達清單載入中');continue}const f=selectRadarFrame(manifest.frames,p.time);if(!f){reports.push(manifest.error||((provider==='jma'?'日本':'臺灣')+'：此時間無可用雷達'));continue}try{let layer:any;if(provider==='jma'){const src=new XYZ({url:'/api/radar?provider=jma&time='+encodeURIComponent(f.time)+'&z={z}&x={x}&y={y}',minZoom:4,maxZoom:10,wrapX:false,crossOrigin:'anonymous',tileLoadFunction:(tile:any,url)=>{fetch(url).then(async r=>{if(r.status===204){tile.getImage().src='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==';tile.getImage().style.opacity='0';return}if(!r.ok)throw Error();const u=URL.createObjectURL(await r.blob());tile.getImage().onload=()=>URL.revokeObjectURL(u);tile.getImage().src=u}).catch(()=>tile.setState(3))}});layer=new TileLayer({source:src,opacity:.001,extent:transform([120,18],'EPSG:4326','EPSG:3857').concat(transform([155,49],'EPSG:4326','EPSG:3857'))});}else{const raw=await cwa(f.time),a=raw.meta;layer=new ImageLayer({source:new ImageStatic({url:raw.url,projection:crs,imageExtent:[a.west-a.step/2,a.south-a.step/2,a.west+(a.cols-.5)*a.step,a.south+(a.rows-.5)*a.step],interpolate:false}),opacity:.001})}if(cancelled)break;pendingLayers.push(layer);m.getLayers().insertAt(2,layer);await new Promise<void>(resolve=>{const timer=setTimeout(resolve,12000);m.once('rendercomplete',()=>{clearTimeout(timer);resolve()});m.render()});reports.push((provider==='jma'?'日本 mm/h':'臺灣 dBZ')+' · '+new Date(f.time).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'})+' UTC+8');}catch(e){reports.push((provider==='jma'?'日本':'臺灣')+'雷達暫未取得，'+String(e))}}
 if(cancelled){pendingLayers.forEach(l=>m.removeLayer(l));return}const previous=layers.current;layers.current=pendingLayers;adopted=true;if(p.playing&&previous.length&&pendingLayers.length){const start=performance.now();const fade=()=>{const f=Math.min(1,(performance.now()-start)/160);pendingLayers.forEach(l=>l.setOpacity(.8*f));previous.forEach(l=>l.setOpacity(.8*(1-f)));if(f<1)requestAnimationFrame(fade);else previous.forEach(l=>m.removeLayer(l))};requestAnimationFrame(fade)}else{previous.forEach(l=>m.removeLayer(l));pendingLayers.forEach(l=>l.setOpacity(.8))}cb.current.onRadarStatus(reports.join('｜'));cb.current.onRadarReady(!p.radars.some(r=>!manifests[r]));for(const t of p.nextTimes.slice(0,2)){if(p.radars.includes('jma')){const f=selectRadarFrame(manifests.jma?.frames||[],t);if(f){const grid=createXYZ({minZoom:4,maxZoom:10}),z=Math.max(4,Math.min(10,Math.round(m.getView().getZoom()||4))),range=grid.getTileRangeForExtentAndZ(m.getView().calculateExtent(m.getSize()),z);let count=0;for(let x=range.minX;x<=range.maxX;x++)for(let y=range.minY;y<=range.maxY;y++)if(++count<=64&&x>=0&&y>=0&&x<2**z&&y<2**z)fetch('/api/radar?provider=jma&time='+encodeURIComponent(f.time)+'&z='+z+'&x='+x+'&y='+y,{cache:'force-cache'}).then(r=>r.arrayBuffer()).catch(()=>{})}}if(p.radars.includes('cwa')){const f=selectRadarFrame(manifests.cwa?.frames||[],t);if(f)cwa(f.time).catch(()=>{})}}})();return()=>{cancelled=true;if(!adopted)pendingLayers.forEach(l=>m.removeLayer(l))}},[p.time,p.radars.join(','),manifests]);
 useEffect(()=>()=>{urls.current.forEach(URL.revokeObjectURL);cache.current.clear()},[]);
}
