'use client';
import {useState,useEffect,useRef} from 'react';
import {Satellite,Wind,Layers,ChevronDown,ChevronUp,Plus,Minus,Play,Pause,X,RefreshCw,Info} from 'lucide-react';
import WeatherMap from './ScalarMap';
import {WEATHER_MODELS,WEATHER_FIELDS,availableLevels,colorScale,supportsField,PRODUCTS} from '@/lib/weather-data.mjs';
import {timeLimits} from '@/lib/wind-data.mjs';
import {weatherManifest,loadWeather} from '@/lib/weather-client';
import './weather.css';
const format=(t:string,zone:string)=>new Date(t).toLocaleString('zh-TW',{timeZone:zone==='tw'?'Asia/Taipei':'UTC',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false});
export default function WeatherExplorer(){const [product,setProduct]=useState('scalar'),[extra,setExtra]=useState<any>({}),[station,setStation]=useState<any>(null),[stationBusy,setStationBusy]=useState(false),[model,setModel]=useState('gfs'),[field,setField]=useState('humidity'),[level,setLevel]=useState(850),[meta,setMeta]=useState<any>(null),[step,setStep]=useState(0),[data,setData]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[point,setPoint]=useState<any>(null),[expanded,setExpanded]=useState(false),[timeOpen,setTimeOpen]=useState(false),[contours,setContours]=useState(true),[play,setPlay]=useState(false),[zone,setZone]=useState('tw'),[info,setInfo]=useState(false),[refresh,setRefresh]=useState(0),[date,setDate]=useState(timeLimits('history',null).max),[hour,setHour]=useState(0);const api=useRef<any>(null),manifestKey=useRef(''),commit=useRef(''),dialog=useRef<HTMLDialogElement>(null);const selection=[model,field,level,refresh].join('|'),chosen=WEATHER_MODELS.find(m=>m.id===model)!,variable=WEATHER_FIELDS.find(f=>f.id===field)!,history=model==='era5',limits=timeLimits('history',null);
 useEffect(()=>{setTimeOpen(!window.matchMedia('(max-width:720px)').matches)},[]);
 useEffect(()=>{setStation(null)},[point]);
 useEffect(()=>{if(info)dialog.current?.showModal()},[info]);
 useEffect(()=>{const c=new AbortController();let alive=true;setMeta(null);setData(null);setPoint(null);setError('');setBusy(true);setPlay(false);setStep(0);manifestKey.current='';if(history){setBusy(false);manifestKey.current=selection;setMeta({run:'',maxStep:23,cadence:1});return()=>c.abort()}weatherManifest(model,field,level,c.signal).then(m=>{if(alive){manifestKey.current=selection;setStep(m.minStep||0);setMeta(m)}}).catch(e=>{if(alive){setError(e.message);setBusy(false)}});return()=>{alive=false;c.abort()}},[selection]);
 const key=[selection,meta?.run,step,date,hour].join('|');
 useEffect(()=>{if(!meta||manifestKey.current!==selection)return;if(commit.current===key){commit.current='';return}const c=new AbortController();let alive=true;setBusy(true);setError('');setPoint(null);loadWeather(model,field,level,meta.run,step,date,hour,c.signal).then(d=>{if(alive){setData(d);setBusy(false)}}).catch(e=>{if(alive){setError(e.message);setBusy(false);setPlay(false)}});return()=>{alive=false;c.abort()}},[key]);
 useEffect(()=>{if(!play||busy||!data||!meta)return;const next=history?hour+1:step+meta.cadence;if(next>(history?23:meta.maxStep)){setPlay(false);return}const c=new AbortController();let alive=true;const prepared=loadWeather(model,field,level,meta.run,history?step:next,date,history?next:hour,c.signal);prepared.catch(()=>{});const timer=setTimeout(async()=>{try{const d=await prepared;if(!alive)return;commit.current=[selection,meta.run,history?step:next,date,history?next:hour].join('|');setData(d);setPoint(null);if(history)setHour(next);else setStep(next)}catch(e){if(alive){setPlay(false);setError(e instanceof Error?e.message:'下一張資料尚未就緒')}}},1000);return()=>{alive=false;clearTimeout(timer);c.abort()}},[play,busy,data,meta]);
 const change=(m:string,f:string,l:number)=>{setPlay(false);setModel(m);setField(f);setLevel(availableLevels(m,f).includes(l)?l:availableLevels(m,f)[0]);setPoint(null)};
 useEffect(()=>{setExtra({});setStation(null);if(!data||product==='scalar')return;const c=new AbortController(),p=PRODUCTS.find(p=>p.id===product);(async()=>{const out:any={};if(p?.wind){out.u=await loadWeather(model,'windu',p.wind,meta.run,step,date,hour,c.signal);out.v=await loadWeather(model,'windv',p.wind,meta.run,step,date,hour,c.signal);}if(p?.height)out.height=await loadWeather(model,'height',p.height,meta.run,step,date,hour,c.signal);if(!c.signal.aborted)setExtra(out)})().catch(e=>{if(!c.signal.aborted)setError('疊圖：'+e.message)});return()=>c.abort()},[data,product]);
 const getStation=async()=>{setStationBusy(true);try{const r=await fetch('/api/weather/point?'+new URLSearchParams({model,run:meta.run,step:String(step),lon:String(((point.lon+180)%360+360)%360-180),lat:String(point.lat)}));const j:any=await r.json();if(!r.ok)throw Error(j.error);setStation(j)}catch(e){setError(e instanceof Error?e.message:'單點資料載入失敗')}finally{setStationBusy(false)}};
 const scale=colorScale(field,level),colors=scale.colors.map((c:number[])=>'rgb('+c.join(',')+')'),displayTime=data?.validTime,source=history?'ARCO-ERA5 原始 Zarr':model==='icon'?'DWD 原始 GRIB2 · 官方網格重投影':model==='cmce'?'ECCC 原始 GRIB2 · 完整 21 成員平均':model==='jma'?'JMA GSM 原始 GRIB2':['ecmwf','aifs-single'].includes(model)?'ECMWF Open Data 原始 GRIB2 · CC BY 4.0':'NOAA 原始 GRIB2';
 return <main className="weather-explorer"><header className="weather-header"><a className="weather-brand" href="/"><img src="/images/typhoon-observatory-logo.png" alt="颱風觀測站"/></a><nav aria-label="觀測頁面"><a href="/"><Satellite size={15}/>衛星</a><a href="/wind"><Wind size={15}/>風場</a><a href="/weather" aria-current="page"><Layers size={15}/>天氣圖</a><a href="/radar">雷達</a></nav><button className="weather-icon" onClick={()=>setInfo(true)} aria-label="天氣圖說明"><Info size={19}/></button></header>
 <section className="weather-workspace"><WeatherMap data={data} extra={extra} contours={contours} point={point} onPoint={setPoint} onReady={v=>api.current=v}/>
 <div className="weather-title"><span>全球天氣圖</span><h1>{product==='scalar'?variable.name:PRODUCTS.find(p=>p.id===product)?.name}</h1><p>{chosen.name} · {level?level+' hPa':'地面／整層'}</p></div>
 <section className={'weather-settings '+(expanded?'open':'')} aria-label="天氣圖設定"><button className="weather-settings-toggle" aria-expanded={expanded} onClick={()=>{setExpanded(!expanded);if(!expanded&&window.innerWidth<=720)setTimeOpen(false)}}><Layers size={18}/>{chosen.name} · {variable.name}<ChevronDown size={16}/></button><div className="weather-settings-body"><label>圖表產品<select value={product} onChange={e=>{const p=PRODUCTS.find(p=>p.id===e.target.value)!;setProduct(p.id);if(p.id!=='scalar'){const m=['gfs','ecmwf','aifs-single'].includes(model)?model:'ecmwf';change(m,p.field,p.level)}}}>{PRODUCTS.filter(p=>p.id!=='raincloud').map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>氣象變數<select value={field} onChange={e=>{setProduct('scalar');change(model,e.target.value,level)}}>{WEATHER_FIELDS.map(f=><option disabled={!supportsField(model,f.id)} value={f.id} key={f.id}>{f.name}</option>)}</select></label><label>模式<select value={model} onChange={e=>{setProduct('scalar');change(e.target.value,supportsField(e.target.value,field)?field:'humidity',level)}}>{WEATHER_MODELS.filter(m=>m.api).map(m=><option value={m.id} key={m.id}>{m.name} · {m.provider}</option>)}<optgroup label="尚無已接入的公開原始場">{WEATHER_MODELS.filter(m=>!m.api).map(m=><option disabled key={m.id}>{m.name}</option>)}</optgroup></select></label><div className="weather-row"><label>氣壓層<select value={level} onChange={e=>change(model,field,Number(e.target.value))}>{availableLevels(model,field).map(l=><option key={l} value={l}>{l?l+' hPa':'地面／整層'}</option>)}</select></label><label>定位<select defaultValue="pacific" onChange={e=>api.current?.region(e.target.value)}><option value="pacific">西太平洋</option><option value="taiwan">臺灣</option><option value="world">全球</option><option value="europe">歐洲</option><option value="america">美洲</option></select></label></div>{['height','pressure'].includes(field)&&<label className="weather-checkbox"><input type="checkbox" checked={contours} onChange={e=>setContours(e.target.checked)}/>{field==='pressure'?'等壓線（每 4 hPa）':'等高線（每 60 gpm）'}</label>}<p>{variable.description}</p>{product!=='scalar'&&<p>箭頭表示風的吹往方向；等高線為 500 hPa。疊圖均使用同一模式、起報及有效時間。</p>}<a className="weather-text-button" href="/">颱風官方路徑、警報圈與系集路徑 →</a>{model==='jma'&&field==='humidity'&&<p>JMA 此公開產品的相對濕度最高至 300 hPa。</p>}<button className="weather-text-button" onClick={()=>{setPlay(false);setRefresh(v=>v+1)}}><RefreshCw size={14}/>重新檢查最新資料</button></div></section>
 <div className="weather-zoom"><button aria-label="放大地圖" onClick={()=>api.current?.zoom(1)}><Plus/></button><button aria-label="縮小地圖" onClick={()=>api.current?.zoom(-1)}><Minus/></button></div>
 {point&&<aside className="weather-popup" style={{left:Math.max(10,Math.min(point.width-220,point.x+14)),top:Math.max(10,Math.min(point.height-170,point.y-35))}}><button aria-label="關閉數值" onClick={()=>setPoint(null)}><X size={16}/></button><small>{((point.lon+180)%360+360)%360-180>0?'東經':'西經'} {Math.abs(((point.lon+180)%360+360)%360-180).toFixed(2)}° · {point.lat.toFixed(2)}°</small><strong>{point.value===null?'無資料':point.value.toFixed(field==='height'?0:1)} <em>{variable.unit}</em></strong><small>{level?level+' hPa':'地面／整層'} · 格點內插值</small>{data?.derived&&<small>由比濕與氣溫估算，相對於液態水</small>}{['gfs','ecmwf','aifs-single'].includes(model)&&step>=6&&step%6===0&&<button className="weather-text-button" disabled={stationBusy} onClick={getStation}>{stationBusy?'載入六要素…':'取得此點六要素'}</button>}{station&&<small>氣溫 {station.temperature2m?.toFixed(1)}°C · 濕度 {station.humidity?.toFixed(0)}%<br/>風速 {station.windSpeed?.toFixed(1)} m/s · 風向 {station.windDirection?.toFixed(0)}°<br/>海平面氣壓 {station.pressure?.toFixed(0)} hPa<br/>6h 降水 {station.rain6?.toFixed(1)} mm · 雲量 {station.cloud?.toFixed(0)}%</small>}</aside>}
 <div className="weather-bottom"><section className="weather-legend"><div><b>{variable.name}</b><span>{variable.unit}</span></div><div className="weather-gradient" style={{background:`linear-gradient(90deg,${colors.join(',')})`}}/><div className="weather-ticks"><span>{scale.min}</span><span>{Math.round((scale.min+scale.max)/2)}</span><span>{scale.max}</span></div></section>
 <section className="weather-time"><div className="weather-time-head"><button aria-expanded={timeOpen} onClick={()=>{setTimeOpen(!timeOpen);if(!timeOpen&&window.innerWidth<=720)setExpanded(false)}}>{timeOpen?<ChevronDown size={16}/>:<ChevronUp size={16}/>}<span>{displayTime?format(displayTime,zone):'準備天氣圖'}<small>{zone==='tw'?'UTC+8 臺灣':'UTC'} · {history?'再分析':'有效時間'}</small></span></button><button className="weather-play" disabled={busy||!data||Boolean(error)} aria-label={play?'暫停動畫':'播放動畫'} onClick={()=>setPlay(!play)}>{play?<Pause size={18}/>:<Play size={18}/>}</button></div><div className={'weather-time-body '+(timeOpen?'open':'')}><div className="weather-row"><label>顯示時區<select value={zone} onChange={e=>setZone(e.target.value)}><option value="tw">臺灣 UTC+8</option><option value="utc">UTC</option></select></label>{history?<label>再分析日期（UTC）<input type="date" min={limits.min} max={limits.max} value={date} onChange={e=>{if(e.target.value>=limits.min&&e.target.value<=limits.max){setPlay(false);setDate(e.target.value)}}}/></label>:<span className="weather-run">起報 {meta?format(meta.run.slice(0,4)+'-'+meta.run.slice(4,6)+'-'+meta.run.slice(6,8)+'T'+meta.run.slice(8)+':00:00Z',zone):'載入中'}</span>}</div><input aria-label={history?'再分析小時':'預報時效'} type="range" min={history?0:meta?.minStep||0} max={history?23:meta?.maxStep||0} step={history?1:meta?.cadence||3} value={history?hour:step} disabled={!meta} onChange={e=>{setPlay(false);history?setHour(Number(e.target.value)):setStep(Number(e.target.value))}}/><div className="weather-ticks"><span>{history?'00:00 UTC':'起報 +'+(meta?.minStep||0)+'h'}</span><span>{history?`${hour}:00 UTC`:`選取 +${step}h`}</span><span>{history?'23:00 UTC':`+${meta?.maxStep||0}h`}</span></div><p>{source}{data?' · '+data.grid.lonStep+'° 格點':''}{data?.derived?' · 相對濕度由 q/T 診斷（液態水定義）':''}</p><p>高空圖層可能包含地形以下的外推值；放大地圖不會增加原始資料解析度。</p></div>{busy&&<div role="status" className="weather-status">正在載入原始資料{data?'，地圖暫留上一張（以上方有效時間為準）':''}…</div>}{error&&<div role="alert" className="weather-error">{error} <button onClick={()=>setRefresh(v=>v+1)}>重試</button></div>}</section></div>
 </section><dialog ref={dialog} onClose={()=>setInfo(false)} className="weather-dialog"><button onClick={()=>dialog.current?.close()} aria-label="關閉說明"><X/></button><h2>如何閱讀天氣圖</h2><p>相對濕度：模式原始相對濕度；AIFS、AIGEFS 與 ERA5 由比濕、氣溫及氣壓計算相對於液態水的濕度，與原生冰相／混合相定義可能不同。色階超過 100% 仍以最高色顯示，點選可查看原始數值。</p><p>位勢高度：等壓面的高度，單位為位勢公尺（gpm）。等高線每 60 gpm；辨識槽、脊時應同時考慮緯度與環流配置。</p><p>海平面氣壓：等壓線每 4 hPa，較粗線每 20 hPa；標籤單位為 hPa。線越密集，水平氣壓梯度通常越大，但不能只用等壓線推算當地實際風速。</p><p>氣溫：選定氣壓層的溫度。這三個圖層都不是地面實測，也不代表颱風官方強度。</p><p>GEFS、GEPS、AIGEFS 為系集平均；ERA5 為歷史再分析，提供最近三個月、約延遲六天的資料。預報範圍依各模式原生時效。</p><p>點擊地圖查看格點內插數值。手機上可收合設定與時間控制；地圖可自由移動至其他地區。模式來源缺測時會顯示錯誤，不會以另一模式替代。</p><p>SD3、TD 與 WNC 是附圖網站的產品名稱，目前沒有已驗證的公開原始接口，不會以其他模式冒名替代。颱風官方路徑與警報圈請使用衛星頁面的 JMA 圖層；模式預報誤差需要歷史起報與實際路徑回測，不以當下系集離散度冒充。</p><p>資料來源：NOAA、ECMWF、DWD、ECCC、JMA、ARCO-ERA5。原始資料各自適用其授權與使用條款。</p></dialog></main>
}
