import {formatRun,runDate} from './gfs-raw.mjs';
const validRun=run=>typeof run==='string'&&Number.isFinite(+runDate(run))&&formatRun(runDate(run))===run;
export const ECMWF_RAW={aigefs:{model:'aigefs',cadence:6,max:384},gefs:{model:'gefs',cadence:3,max:384},ecmwf:{model:'ifs',stream:'oper',type:'fc',cadence:3,max:240},'aifs-single':{model:'aifs-single',stream:'oper',type:'fc',cadence:6,max:360}};
export function ecmwfPath(id,run,step){const c=ECMWF_RAW[id];if(!validRun(run)||!c||!/^\d{8}(00|06|12|18)$/.test(run)||!Number.isInteger(step)||step<0||step>c.max||step%c.cadence)throw Error('無效 ECMWF 原始資料請求');return `https://storage.googleapis.com/ecmwf-open-data/${run.slice(0,8)}/${run.slice(8)}z/${c.model}/0p25/${c.stream}/${run}0000-${step}h-${c.stream}-${c.type}`}
export function ecmwfRanges(text,level){const rows=text.trim().split('\n').map(s=>JSON.parse(s)),params=level.endsWith('hPa')?['u','v','sp']:[`${parseInt(level)}u`,`${parseInt(level)}v`];return params.map(param=>{const r=rows.find(r=>r.param===param&&(param==='sp'||!level.endsWith('hPa')||+r.levelist===parseInt(level)));if(!r)throw Error(`原始來源未提供 ${param} ${level}`);const start=+r._offset,length=+r._length;if(!Number.isSafeInteger(start)||!Number.isSafeInteger(length)||start<0||length<16||length>8000000)throw Error('來源索引無效');return {start,end:start+length-1}})}
export function iconURL(run,step,field,level){if(!validRun(run)||!/^\d{8}(00|06|12|18)$/.test(run)||!Number.isInteger(step)||step<0||step>180||(step>78&&step%3)||!['u','v','p'].includes(field)||!(level==='10m'||/^(925|850|700|500|300|250|200)hPa$/.test(level)))throw Error('無效 ICON 原始請求');const folder=field==='p'?'ps':level==='10m'?field+'_10m':field,name=folder.toUpperCase(),layer=field!=='p'&&level.endsWith('hPa')?'pressure-level':'single-level',suffix=layer==='pressure-level'?parseInt(level)+'_'+name:name;return `https://opendata.dwd.de/weather/nwp/icon/grib/${run.slice(8)}/${folder}/icon_global_icosahedral_${layer}_${run}_${String(step).padStart(3,'0')}_${suffix}.grib2.bz2`}

export function gefsPath(run,step){if(!validRun(run)||!/^\d{8}(00|06|12|18)$/.test(run)||!Number.isInteger(step)||step<0||step>384||step%(step>240?6:3))throw Error('無效 GEFS 原始請求');return `https://noaa-gefs-pds.s3.amazonaws.com/gefs.${run.slice(0,8)}/${run.slice(8)}/atmos/pgrb2ap5/geavg.t${run.slice(8)}z.pgrb2a.0p50.f${String(step).padStart(3,'0')}`}
export function gepsURL(run,step,field,level){if(!validRun(run)||!/^\d{8}(00|12)$/.test(run)||!Number.isInteger(step)||step<0||step>384||step%(step>192?6:3)||!['u','v','p'].includes(field)||!(level==='10m'||/^(925|850|700|500|300|250|200)hPa$/.test(level)))throw Error('無效 GEPS 原始請求');const variable=field==='p'?'PRES':field==='u'?'UGRD':'VGRD',layer=field==='p'?'SFC_0':level==='10m'?'TGL_10m':'ISBL_'+String(parseInt(level)).padStart(4,'0');return `https://dd.weather.gc.ca/today/ensemble/geps/grib2/raw/${run.slice(8)}/${String(step).padStart(3,'0')}/CMC_geps-raw_${variable}_${layer}_latlon0p5x0p5_${run}_P${String(step).padStart(3,'0')}_allmbrs.grib2`}
export function aigefsPath(run,step){if(!validRun(run)||!/^\d{8}(00|06|12|18)$/.test(run)||!Number.isInteger(step)||step<0||step>384||step%6)throw Error('無效 AIGEFS 原始請求');return `https://nomads.ncep.noaa.gov/pub/data/nccf/com/aigefs/prod/aigefs.${run.slice(0,8)}/${run.slice(8)}/ensstat/products/atmos/grib2/aigefs.t${run.slice(8)}z.sfc.avg.f${String(step).padStart(3,'0')}.grib2`}
