// Raw GRIB decoding stays on Node: mobile browsers do not need Memory64 support.
import {readFile} from 'node:fs/promises';
import {gunzipSync,gzipSync} from 'node:zlib';
import {createRequire} from 'node:module';
import Bunzip from 'seek-bzip';
import {fetchWeather} from './weather-raw.mjs';
import {decodeWeather} from './weather-decode.mjs';
// @ts-ignore Vendored ecCodes API has no TypeScript declarations.
import {createEccodes} from '../public/vendor/eccodes-api.mjs';
// @ts-ignore Vendored Emscripten runtime has no TypeScript declarations.
import runtime from '../public/vendor/eccodes-runtime.mjs';
let engine:Promise<any>|undefined,indices:Promise<Uint32Array>|undefined;
function decoder(){if(!engine){engine=(async()=>{(globalThis as any).require=createRequire(process.cwd()+'/package.json');(globalThis as any).__dirname=process.cwd();(globalThis as any).__filename=process.cwd()+'/package.json';const compiled=await WebAssembly.compile(gunzipSync(await readFile(process.cwd()+'/public/vendor/eccodes.wasm.gz')));return createEccodes(runtime,{instantiateWasm:(imports:any,receive:any)=>{const instance=new WebAssembly.Instance(compiled,imports);receive(instance,compiled);return instance.exports}})})();engine.catch(()=>{engine=undefined})}return engine}
async function decodePacket(bytes:Uint8Array){const n=new DataView(bytes.buffer,bytes.byteOffset).getUint32(0,true),meta=JSON.parse(new TextDecoder().decode(bytes.subarray(4,4+n)));let off=4+n;const parts=meta.sizes.map((size:number)=>{const b=bytes.subarray(off,off+size);off+=size;return meta.model==='icon'?new Uint8Array(Bunzip.decode(Buffer.from(b))):b});if(meta.model==='icon'&&!indices)indices=readFile(process.cwd()+'/public/vendor/icon-world-025.indices.gz').then(b=>{const u=gunzipSync(b);return new Uint32Array(u.buffer.slice(u.byteOffset,u.byteOffset+u.byteLength))});const d=await decoder(),map=meta.model==='icon'?await indices:undefined,result=decodeWeather(parts,meta,d,map);return result;}
export function encodeWeather(result:any){const {values,...header}=result;const json=new TextEncoder().encode(JSON.stringify({...header,decoded:true})),out=new Uint8Array(4+json.length+values.byteLength);new DataView(out.buffer).setUint32(0,json.length,true);out.set(json,4);out.set(new Uint8Array(values.buffer),4+json.length);return new Uint8Array(gzipSync(out));}

const grids=new Map<string,any>(),pending=new Map<string,Promise<any>>();
export async function decodedWeather(model:string,field:string,level:number,run:string,step:number):Promise<any>{const key=[model,field,level,run,step].join('|');if(grids.has(key))return grids.get(key);if(pending.has(key))return pending.get(key);const task=(async()=>{let result=await decodePacket(await fetchWeather(model,field,level,run,step));if(field.startsWith('rain')){const start=field==='rainTotal'?0:step-(field==='rain24'?24:6);if(start<0)throw Error('預報尚未涵蓋完整累積時段');let values=new Float32Array(result.values),cursor=result.period.start;if(cursor<start){const before=await decodedWeather(model,'rainTotal',0,run,start);if(before.period.start!==cursor)throw Error('累積降水起點不一致');for(let i=0;i<values.length;i++)values[i]=Number.isFinite(values[i])&&Number.isFinite(before.values[i])?Math.max(0,values[i]-before.values[i]):NaN;cursor=start;}while(cursor>start){const prev=await decodePacket(await fetchWeather(model,'rain6',0,run,cursor));if(prev.period.end!==cursor||prev.period.start<start||prev.period.start>=cursor||JSON.stringify(prev.grid)!==JSON.stringify(result.grid))throw Error('累積降水時段有缺口或網格不一致');for(let i=0;i<values.length;i++)values[i]=Number.isFinite(values[i])&&Number.isFinite(prev.values[i])?values[i]+prev.values[i]:NaN;cursor=prev.period.start;}result={...result,values,period:{start,end:step}};}grids.set(key,result);while(grids.size>8)grids.delete(grids.keys().next().value!);return result})();pending.set(key,task);try{return await task}finally{pending.delete(key)}}
export async function prepareWeather(bytes:Uint8Array){return encodeWeather(await decodePacket(bytes));}
