import {formatRun,runDate,gfsUrl} from './gfs-raw.mjs';
import {ecmwfPath,gefsPath,aigefsPath} from './raw-sources.mjs';
import {jmaURL,jmaRange} from './jma-raw.mjs';
import {validSelection,minimumStep} from './weather-data.mjs';
import {edgeCache} from './edge-cache.mjs';
export const CONFIG={gfs:{max:384,cycle:6,step:3},ecmwf:{max:240,cycle:6,step:6},'aifs-single':{max:360,cycle:6,step:6},gefs:{max:384,cycle:6,step:6},aigefs:{max:384,cycle:6,step:6},icon:{max:180,cycle:6,step:3},cmce:{max:384,cycle:12,step:6},jma:{max:132,cycle:6,step:6}};
export function validateRequest(model,field,level,run,step){const c=CONFIG[model];if(!c||!validSelection(model,field,level)||!/^\d{8}(00|06|12|18)$/.test(run)||!Number.isFinite(+runDate(run))||formatRun(runDate(run))!==run||+run.slice(8)%c.cycle||!Number.isInteger(step)||step<0||step>c.max||step%c.step)throw Error('模式、變數、氣壓層或預報時效無效')}
export function indexedRanges(text,model,field,level){const ec=['ecmwf','aifs-single'].includes(model),rows=text.trim().split('\n').map(s=>ec?JSON.parse(s):s.split(':')),surface={temperature2m:['2t','TMP','2 m above ground'],dewpoint2m:['2d','DPT','2 m above ground'],pressure:['msl','PRMSL','mean sea level'],cloud:['tcc','TCDC','entire atmosphere'],cape:['mucape','CAPE','surface'],u10:['10u','UGRD','10 m above ground'],v10:['10v','VGRD','10 m above ground']};let names;if(field.startsWith('rain'))names=[ec?'tp':'APCP'];else if(surface[field])names=[surface[field][ec?0:1]];else if(field==='height')names=[ec?'gh':'HGT'];else if(field==='temperature')names=[ec?'t':'TMP'];else if(field==='windu')names=[ec?'u':'UGRD'];else if(field==='windv')names=[ec?'v':'VGRD'];else names=model==='aifs-single'?['q','t']:model==='aigefs'?['SPFH','TMP']:ec?['r']:['RH'];return names.map(param=>{const layer=field.startsWith('rain')?'surface':surface[field]?.[2]||`${level} mb`,matches=rows.map((r,i)=>({r,i})).filter(({r})=>ec?r.param===param&&((level===0&&!r.levelist)||+r.levelist===level):r[3]===param&&r[4]===layer),entry=matches.at(-1);if(!entry)throw Error(`原始來源未提供 ${param} ${level===0?'地面':level+' hPa'}`);const {r,i}=entry,start=+(ec?r._offset:r[1]),end=ec?start+Number(r._length)-1:rows[i+1]?+rows[i+1][1]-1:NaN;if(!Number.isSafeInteger(start)||!Number.isSafeInteger(end)||start<0||end<start||end-start>10000000)throw Error('原始欄位索引不完整');return {start,end}})}
export function indexedURL(model,run,step){return model==='gfs'?gfsUrl(run,step):model==='gefs'?gefsPath(run,step):model==='aigefs'?aigefsPath(run,step).replace('.sfc.','.pres.'):ecmwfPath(model,run,step)}
export function singleURL(model,run,step,field,level){if(model==='icon'){const v={humidity:'relhum',height:'fi',temperature:'t',windu:'u',windv:'v'}[field];return `https://opendata.dwd.de/weather/nwp/icon/grib/${run.slice(8)}/${v}/icon_global_icosahedral_pressure-level_${run}_${String(step).padStart(3,'0')}_${level}_${v.toUpperCase()}.grib2.bz2`}const v={humidity:'RH',height:'HGT',temperature:'TMP',windu:'UGRD',windv:'VGRD'}[field];return `https://dd.weather.gc.ca/today/ensemble/geps/grib2/raw/${run.slice(8)}/${String(step).padStart(3,'0')}/CMC_geps-raw_${v}_ISBL_${String(level).padStart(4,'0')}_latlon0p5x0p5_${run}_P${String(step).padStart(3,'0')}_allmbrs.grib2`}
const memory=new Map();let total=0;
export async function readRaw(url,range){const key=url+(range?'?weather-range='+range.start+'-'+range.end:''),hit=memory.get(key);if(hit)return hit.slice();const cached=await edgeCache.match(new Request(key));if(cached)return new Uint8Array(await cached.arrayBuffer());let response;for(let attempt=0;attempt<2;attempt++){response=await fetch(url,{headers:range?{Range:`bytes=${range.start}-${range.end}`}:{},signal:AbortSignal.timeout(30000)});if(response.ok)break;if(response.status<500&&response.status!==429)break}if(!response.ok)throw Error(`原始來源回覆 ${response.status}`);if(range&&(response.status!==206||!response.headers.get('content-range')?.startsWith(`bytes ${range.start}-${range.end}/`)))throw Error('原始來源未回覆指定欄位範圍');const b=new Uint8Array(await response.arrayBuffer());if(b.length>18000000||range&&b.length!==range.end-range.start+1)throw Error('原始資料大小不符');while(total+b.length>40000000&&memory.size){const k=memory.keys().next().value;total-=memory.get(k).length;memory.delete(k)}memory.set(key,b);total+=b.length;await edgeCache.put(new Request(key),new Response(b.slice(),{headers:{'Cache-Control':'public,max-age=86400'}}));return b}
export function jmaScalarRange(step,level,field){const base=jmaRange(step,level+'hPa').start,offset=field==='windu'?0:field==='windv'?1:field==='temperature'?2:field==='humidity'?3:level>=300?4:3;return {start:base+offset*62706,end:base+(offset+1)*62706-1}}
export function jmaScalarMessage(header,f,step,level,field){const v=new DataView(f.buffer,f.byteOffset,f.byteLength),code={humidity:[1,1],height:[3,5],temperature:[0,0],windu:[2,2],windv:[2,3]}[field];if(header.length!==109||new TextDecoder().decode(header.slice(0,4))!=='GRIB'||f.length!==62706||v.getUint32(0)!==34||f[4]!==4||f[9]!==code[0]||f[10]!==code[1]||v.getUint32(18)!==step||f[22]!==100||v.getUint32(24)!==level)throw Error('JMA 原始欄位／時間／高度驗證失敗');const b=new Uint8Array(109+f.length+4);b.set(header);new DataView(b.buffer).setBigUint64(8,BigInt(b.length));b.set(f,109);b.set([55,55,55,55],b.length-4);return b}
export async function fetchWeather(model,field,level,run,step){validateRequest(model,field,level,run,step);let parts;
if(model==='jma'){const url=jmaURL(run),[h,f]=await Promise.all([readRaw(url,{start:0,end:108}),readRaw(url,jmaScalarRange(step,level,field))]);parts=[jmaScalarMessage(h,f,step,level,field)]}
else if(['icon','cmce'].includes(model))parts=[await readRaw(singleURL(model,run,step,field,level))];
else{const url=indexedURL(model,run,step),ec=['ecmwf','aifs-single'].includes(model),idx=new TextDecoder().decode(await readRaw(url+(ec?'.index':'.idx'))),ranges=indexedRanges(idx,model,field,level);parts=await Promise.all(ranges.map(r=>readRaw(url+(ec?'.grib2':''),r)))}
const meta={model,field,level,run,step,validTime:new Date(+runDate(run)+step*3600000).toISOString(),derived:field==='humidity'&&['aifs-single','aigefs'].includes(model),sizes:parts.map(b=>b.length)},json=new TextEncoder().encode(JSON.stringify(meta)),out=new Uint8Array(4+json.length+parts.reduce((n,b)=>n+b.length,0));new DataView(out.buffer).setUint32(0,json.length,true);out.set(json,4);let i=4+json.length;for(const b of parts){out.set(b,i);i+=b.length}return out}
const latest=new Map();
export async function latestWeather(model,field,level){if(!CONFIG[model]||!validSelection(model,field,level))throw Error('此模式未接入此原始欄位');const key=[model,field,level].join('|'),hit=latest.get(key);if(hit&&hit.until>Date.now())return hit.data;const c=CONFIG[model],d=new Date(Date.now()-7*3600000);d.setUTCMinutes(0,0,0);d.setUTCHours(Math.floor(d.getUTCHours()/c.cycle)*c.cycle);let last;for(let i=0;i<3;i++){const run=formatRun(new Date(+d-i*c.cycle*3600000));try{await fetchWeather(model,field,level,run,minimumStep(field));const data={model,run,maxStep:model==='ecmwf'&&['06','18'].includes(run.slice(8))?144:c.max,cadence:field.startsWith('rain')?6:c.step,minStep:minimumStep(field)};latest.set(key,{data,until:Date.now()+600000});return data}catch(e){last=e}}throw Error('最近三個起報暫未取得完整欄位：'+last?.message)}
