import {splitMessages,parseFields,decodeFieldValues} from '@azohra/meteo.grib';
import {decodeJ2k} from '@azohra/meteo.j2k';
import {relativeHumidity,convertScalar} from './weather-data.mjs';
// The same decoder is used by the browser worker and the live-source verification script.
export function decodeWeather(parts,meta,d,iconMap){const fields={},members=new Set();let geometry=null,period=null,sourceUnits=null,sourceName=null;
 for(const raw of parts){const parsed=meta.model==='cmce'?splitMessages(raw).flatMap(parseFields):[];let at=0;d.writeFile('/weather.grib',raw);try{d.forEachMessage('/weather.grib',h=>{const short=h.getString('shortName'),expected=meta.derived?['q','t']:meta.field==='height'?['gh','z']:meta.field==='temperature'?['t']:({temperature2m:['2t'],dewpoint2m:['2d'],pressure:['msl','prmsl'],cloud:['tcc'],cape:['cape','mucape'],u10:['10u'],v10:['10v'],windu:['u'],windv:['v'],rain6:['tp'],rain24:['tp'],rainTotal:['tp']}[meta.field]||['r']);if(!expected.includes(short))throw Error('來源不是所選天氣變數：'+short);if(String(h.getLong('dataDate'))+String(h.getLong('dataTime')).padStart(4,'0').slice(0,2)!==meta.run||h.getLong('endStep')!==meta.step)throw Error('原始資料的起報／有效時間不符');const type=h.getString('typeOfLevel'),lv=h.getLong('level');if(meta.level>0?(lv!==meta.level||type!=='isobaricInhPa'):['temperature2m','dewpoint2m'].includes(meta.field)?type!=='heightAboveGround'||lv!==2:['u10','v10'].includes(meta.field)?type!=='heightAboveGround'||lv!==10:meta.field==='pressure'?type!=='meanSea':meta.field==='cloud'?!['entireAtmosphere','atmosphere'].includes(type):meta.field==='cape'?!['surface','mostUnstableParcel'].includes(type):type!=='surface')throw Error('原始資料的高度類型不符');if(meta.field.startsWith('rain')){const p={start:h.getLong('startStep'),end:h.getLong('endStep')};if(h.getString('stepType')!=='accum'||p.end!==meta.step||p.start<0||p.end<p.start)throw Error('原始降水累積時段不符');if(period&&JSON.stringify(period)!==JSON.stringify(p))throw Error('原始累積時段不一致');period=p}
 const icon=meta.model==='icon';let g;if(icon){if(h.getString('gridType')!=='unstructured_grid'||h.getLong('numberOfDataPoints')!==2949120||h.getString('uuidOfHGrid')!=='a27b8de618c411e4820ab5b098c6a5c0'||iconMap?.length!==1440*721)throw Error('ICON 網格識別不符');g={ni:1440,nj:721,north:90,south:-90,west:-180,dx:.25,dy:.25,positive:true,icon:true}}else{if(h.getString('gridType')!=='regular_ll'||h.getLong('iScansNegatively')||h.getLong('jPointsAreConsecutive')||h.getLong('alternativeRowScanning'))throw Error('來源網格排列不支援');const first=h.getDouble('latitudeOfFirstGridPointInDegrees'),last=h.getDouble('latitudeOfLastGridPointInDegrees');g={ni:h.getLong('Ni'),nj:h.getLong('Nj'),north:Math.max(first,last),south:Math.min(first,last),west:h.getDouble('longitudeOfFirstGridPointInDegrees'),dx:h.getDouble('iDirectionIncrementInDegrees'),dy:h.getDouble('jDirectionIncrementInDegrees'),positive:Boolean(h.getLong('jScansPositively'))};if(Math.abs(g.ni*g.dx-360)>.01)throw Error('非完整全球格點')}
 if(geometry&&JSON.stringify(g)!==JSON.stringify(geometry))throw Error('原始欄位網格不一致');geometry=g;
 const values=meta.model==='cmce'?decodeFieldValues(parsed[at++],{decodeJ2k,missingValue:NaN}).values:h.getDoubleArray('values');if(values.length!==(icon?2949120:g.ni*g.nj))throw Error('原始格點數目不符');
 const units=h.getString('units');sourceUnits=units;sourceName=h.getString('name');if(meta.field.startsWith('rain')&&!['m','kg m**-2','kg m-2','mm'].includes(units))throw Error('原始降水單位不符');if(['2t','2d'].includes(short)&&units!=='K'||['u','v','10u','10v'].includes(short)&&units!=='m s**-1'||['msl','prmsl'].includes(short)&&units!=='Pa'||['cape','mucape'].includes(short)&&units!=='J kg**-1'||short==='tcc'&&!['%','(0 - 1)'].includes(units)||short==='t'&&units!=='K'||short==='r'&&units!=='%'||short==='gh'&&!['gpm','m'].includes(units)||short==='q'&&!['kg kg**-1','kg kg-1'].includes(units)||short==='z'&&!['m**2 s**-2','m2 s-2'].includes(units))throw Error('來源物理單位不符：'+units);
 const member=meta.model==='cmce'?h.getLong('perturbationNumber'):0;if(meta.model==='cmce'&&(member<0||member>20||h.getLong('numberOfForecastsInEnsemble')!==21))throw Error('GEPS 成員定義不符');const memberKey=short+'|'+member;if(members.has(memberKey))throw Error('重複的模式成員');members.add(memberKey);
 const a=fields[short]||(fields[short]={sum:new Float64Array(values.length),count:new Uint8Array(values.length),n:0});a.n++;const missing=h.getLong('bitmapPresent')?h.getDouble('missingValue'):NaN;for(let i=0;i<values.length;i++){const v=values[i];if(Number.isFinite(v)&&Math.abs(v)<1e8&&v!==missing){a.sum[i]+=v;a.count[i]++}}});}finally{d._module.FS.unlink('/weather.grib')}}
 const {ni,nj,north,south,west,dx,dy,positive,icon}=geometry||{};if(!ni)throw Error('未取得原始場');const required=meta.model==='cmce'?21:1;if(Object.values(fields).some(f=>f.n!==required)||meta.derived&&(!fields.q||!fields.t))throw Error('原始成員或必要欄位缺漏');const short=Object.keys(fields)[0],values=new Float32Array((ni+1)*nj);let valid=0;for(let j=0;j<nj;j++)for(let i=0;i<=ni;i++){const k=j*(ni+1)+i,src=icon?iconMap[j*ni+i%ni]:(positive?j:nj-1-j)*ni+i%ni;const val=s=>fields[s]?.count[src]===required?fields[s].sum[src]/required:NaN;let v=meta.derived?relativeHumidity(val('q'),val('t'),meta.level):convertScalar(val(short),short,meta.field);if(meta.field.startsWith('rain')&&sourceUnits==='m')v*=1000;if(meta.field==='cloud'&&sourceUnits==='(0 - 1)')v*=100;values[k]=v;if(Number.isFinite(v))valid++}if(!valid)throw Error('原始場沒有有效數值');return {...meta,period,sourceUnits,sourceVariable:sourceName,grid:{west,east:west+360,south,north,cols:ni+1,rows:nj,lonStep:dx,latStep:dy},values,validFraction:valid/values.length}}
