import {edgeCache} from '@/lib/edge-cache.mjs';
import {ECMWF_RAW,ecmwfPath,ecmwfRanges,gefsPath,aigefsPath} from '@/lib/raw-sources.mjs';
import {formatRun,runDate,windRanges} from '@/lib/gfs-raw.mjs';
import {WIND_LEVELS} from '@/lib/wind-data.mjs';
const memory=new Map<string,ArrayBuffer>();
async function get(url:string,range?:string){const key=url+'|'+(range||'');const hit=memory.get(key);if(hit)return hit.slice(0);const edge=edgeCache,k=new Request(url+(range?'?rawrange='+range.replace(/[^0-9-]/g,''):''));const cached=await edge?.match(k);if(cached)return cached.arrayBuffer();const r=await fetch(url,{headers:range?{Range:range}:{},signal:AbortSignal.timeout(50000)});if(!r.ok||(range&&r.status!==206))throw Error('原始來源回覆 '+r.status);if(range&&!r.headers.get('content-range')?.startsWith('bytes '+range.slice(6)+'/'))throw Error('來源位元組範圍不符');const body=await r.arrayBuffer();if(body.byteLength>12000000)throw Error('原始欄位過大');memory.set(key,body);if(memory.size>12)memory.delete(memory.keys().next().value!);if(edge)await edge.put(k,new Response(body.slice(0),{headers:{'Cache-Control':'public,max-age=86400'}}));return body}
export async function GET(req:Request){try{const q=new URL(req.url).searchParams,id=q.get('model')||'',c=(ECMWF_RAW as Record<string,any>)[id];if(!c)return Response.json({error:'此模型尚未驗證公開原始風場來源'},{status:400});
 const path=(run:string,step:number)=>id==='aigefs'?aigefsPath(run,step):id==='gefs'?gefsPath(run,step):ecmwfPath(id,run,step),indexSuffix=['gefs','aigefs'].includes(id)?'.idx':'.index';
 if(q.get('latest')==='1'){const d=new Date(Date.now()-6*3600000);d.setUTCMinutes(0,0,0);d.setUTCHours(Math.floor(d.getUTCHours()/12)*12);let run='';for(let i=0;i<3;i++){const candidate=formatRun(new Date(+d-i*12*3600000));try{await get(path(candidate,0)+indexSuffix);run=candidate;break}catch{}}if(!run)throw Error('來源最新起報尚未到齊');return Response.json({run,cadence:c.cadence,maxStep:c.max,cadenceAfter:id==='gefs'?240:null},{headers:{'Cache-Control':'public,max-age=900'}})}
 const run=q.get('run')||'',step=Number(q.get('step')),level=q.get('level')||'10m';if((id==='aigefs'&&level!=='10m')||!WIND_LEVELS.some(l=>l.id===level)||!q.has('step'))return Response.json({error:'無效高度／時效'},{status:400});let base;try{base=path(run,step);const age=Date.now()-+runDate(run);if(!Number.isFinite(age)||age<0||age>3*86400000)throw Error()}catch{return Response.json({error:'只接受來源保留期間的有效起報'},{status:400})}
 const idx=new TextDecoder().decode(await get(base+indexSuffix)),ranges=['gefs','aigefs'].includes(id)?windRanges(idx,level):ecmwfRanges(idx,level),parts=await Promise.all(ranges.map(r=>get(base+(['gefs','aigefs'].includes(id)?'':'.grib2'),`bytes=${r.start}-${r.end}`)));
 const out=new Uint8Array(parts.reduce((n,b)=>n+b.byteLength,0));let off=0;for(const part of parts){out.set(new Uint8Array(part),off);off+=part.byteLength}return new Response(out,{headers:{'Content-Type':'application/octet-stream','Cache-Control':'public,max-age=86400'}});
 }catch(e){return Response.json({error:e instanceof Error?e.message:'原始資料載入失敗；未切換其他模式'},{status:502})}}
